=== MegaMek/megamek/megamek/data/forcegenerator/faction_rules/formationRulesetSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<xs:attributeGroup name="predicateAttributeGroup">
		<xs:attribute name="ifUnitType" type="xs:string" />
		<xs:attribute name="ifWeightClass" type="xs:string" />
		<xs:attribute name="ifRating" type="xs:string" />
		<xs:attribute name="ifFormation" type="xs:string" />
		<xs:attribute name="ifRole" type="xs:string" />
		<xs:attribute name="ifMotive" type="xs:string" />
		<xs:attribute name="ifAugmented" type="xs:boolean" />
		<xs:attribute name="ifDateBetween" type="xs:string" />
		<xs:attribute name="ifTopLevel" type="xs:boolean" />
		<xs:attribute name="ifName" type="xs:string" />
		<xs:attribute name="ifFaction" type="xs:string" />
		<xs:attribute name="ifFlags" type="xs:string" />
		<xs:attribute name="ifIndex" type="xs:string" />
	</xs:attributeGroup>

	<xs:attributeGroup name="assertionAttributeGroup">
		<xs:attribute name="unitType" type="xs:string" />
		<xs:attribute name="weightClass" type="xs:string" />
		<xs:attribute name="rating" type="xs:string" />
		<xs:attribute name="formation" type="xs:string" />
		<xs:attribute name="role" type="xs:string" />
		<xs:attribute name="motive" type="xs:string" />
		<xs:attribute name="augmented" type="xs:boolean" />
		<xs:attribute name="chassis" type="xs:string" />
		<xs:attribute name="model" type="xs:string" />
		<xs:attribute name="variant" type="xs:string" />
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="fluffName" type="xs:string" />
		<xs:attribute name="faction" type="xs:string" />
		<xs:attribute name="flags" type="xs:string" />
	</xs:attributeGroup>

	<xs:group name="ruleGroup">
		<xs:choice>
			<xs:element name="weightClass" type="optionGroupType" />
			<xs:element name="unitType" type="optionGroupType" />
			<xs:element name="chassis" type="optionGroupType" />
			<xs:element name="variant" type="optionGroupType" />
			<xs:element name="motive" type="optionGroupType" />
			<xs:element name="formation" type="optionGroupType" />
			<xs:element name="role" type="optionGroupType" />
			<xs:element name="flags" type="optionGroupType" />
			<xs:element name="changeEschelon" type="optionGroupType" />
		</xs:choice>
	</xs:group>

	<xs:element name="ruleset">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="defaults" />
				<xs:element minOccurs="0" maxOccurs="1" ref="customRanks" />
				<xs:element minOccurs="0" maxOccurs="1" ref="toc" />
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="force" />
			</xs:sequence>
			<xs:attribute name="faction" type="xs:string" />
			<xs:attribute name="parent" type="xs:string" />
			<xs:attribute name="ratingSystem">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="IS|SL|CLAN|ROS" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="defaults">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="unitType">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attributeGroup
									ref="predicateAttributeGroup" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="eschelon">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attributeGroup
									ref="predicateAttributeGroup" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="rankSystem">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attributeGroup
									ref="predicateAttributeGroup" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="rating">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attributeGroup
									ref="predicateAttributeGroup" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="toc">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="1" name="unitType" type="tocType" />
				<xs:element minOccurs="0" maxOccurs="1" name="eschelon" type="tocType" />
				<xs:element minOccurs="0" maxOccurs="1" name="rating" type="tocType" />
				<xs:element minOccurs="0" maxOccurs="1" name="flags" type="tocType" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="customRanks">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" name="base" type="xs:string" />
				<xs:element maxOccurs="unbounded" name="rank">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value=".+:.+" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="force">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" minOccurs="0"
					maxOccurs="unbounded">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attributeGroup
									ref="predicateAttributeGroup" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="co" type="commanderType"
					maxOccurs="unbounded" />
				<xs:element name="xo" type="commanderType"
					minOccurs="0" maxOccurs="unbounded" />
				<xs:group ref="ruleGroup"
					minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="ruleGroup" type="ruleGroupType"
					minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="subforces" type="subforcesType"
					minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="attachedForces"
					type="subforcesType"
					minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>

			<xs:attribute name="eschelon" type="xs:string" use="required" />
			<xs:attribute name="eschName" type="xs:string" />
			<xs:attributeGroup ref="predicateAttributeGroup" />
		</xs:complexType>
	</xs:element>

	<xs:complexType name="tocType">
		<xs:sequence>
			<xs:element name="option" type="tocOptionType"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="tocOptionType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="ifEschelon" type="xs:string" />
				<xs:attributeGroup ref="predicateAttributeGroup" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="commanderType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="position" type="xs:integer" />
				<xs:attribute name="title" type="xs:string" />
				<xs:attribute name="unitType" type="xs:string" />
				<xs:attributeGroup ref="predicateAttributeGroup" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="ruleGroupType">
		<xs:sequence>
			<xs:group ref="ruleGroup" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="optionGroupType">
		<xs:sequence>
			<xs:element name="option" type="optionType"
				maxOccurs="unbounded" />
		</xs:sequence>

		<xs:attributeGroup ref="predicateAttributeGroup" />
	</xs:complexType>

	<xs:complexType name="optionType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="ifYearBetween" type="xs:string" />
				<xs:attribute name="weight" type="xs:integer"
					default="1" />
				<xs:attribute name="num" type="xs:integer" />
				<xs:attributeGroup ref="predicateAttributeGroup" />
				<xs:attributeGroup ref="assertionAttributeGroup" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="subforcesType">
		<xs:choice>
			<xs:element name="asFaction" type="xs:string" />
			<xs:element name="asParent" type="xs:string" />
			<xs:choice maxOccurs="unbounded">
				<xs:element name="subforce" type="subforceType" />
				<xs:element name="subforceOption"
					type="subforceOptionType" />
			</xs:choice>
		</xs:choice>

		<xs:attributeGroup ref="predicateAttributeGroup" />
		<xs:attribute name="generate" type="generateType" />
	</xs:complexType>

	<xs:complexType name="subforceType">
		<xs:simpleContent>
			<xs:extension base="eschelonDefinition">
				<xs:attributeGroup ref="predicateAttributeGroup" />
				<xs:attributeGroup ref="assertionAttributeGroup" />
				<xs:attribute name="num" type="xs:integer" default="1" />
				<xs:attribute name="generate" type="generateType" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:simpleType name="generateType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="model" />
			<xs:enumeration value="chassis" />
			<xs:enumeration value="group" />
			<xs:enumeration value="unit" />
			<xs:enumeration value="" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="eschelonDefinition">
		<xs:restriction base="xs:string">
			<xs:pattern value="([0-9]+|%[A-Z_]+%)[+-^]?" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="subforceOptionType">
		<xs:sequence>
			<xs:element name="option" type="optionType"
				maxOccurs="unbounded" />
		</xs:sequence>

		<xs:attributeGroup ref="predicateAttributeGroup" />
		<xs:attribute name="generate" type="generateType" />
	</xs:complexType>

</xs:schema>

=== MegaMek/megamek/megamek/data/forcegenerator/faction_rules/MOC.xml
<?xml version="1.0" encoding="utf-8"?>

<!-- MOC units are structured around a Mek regiment with an armor guard of 1-2
battalions and an infantry guard ranging from a battalion to a regiment. Air
support is very weak, with most of the ASFs attached to central command and assigned
as needed. Prior to the Trinity Alliance, only the Royal Guard had any permanent air
guard and that was typically limited to a single flight. After 3060 the Magistracy
made a concerted effort to expand aerospace forces, adding an air guard to Chasseurs Ã 
Cheval regiments as well and averaging just under a squadron by the Jihad, and
expanding to a full wing per regiment by the Dark Age. -->

<ruleset faction="MOC" parent="Periphery" ratingSystem="IS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="formationRulesetSchema.xsd">

	<defaults>
		<unitType ifFaction="MOC.RC" ifDateBetween=",3062">Infantry</unitType>
		<unitType>Mek</unitType>
		<eschelon>%REGIMENT%</eschelon>
		<rankSystem>%RANK_MOC%</rankSystem>
		<rating>C</rating>
	</defaults>

	<toc>
		<unitType>
			<option ifDateBetween="3051,">Mek,Tank,VTOL,Infantry,BattleArmor,AeroSpaceFighter,Conventional Fighter</option>
			<option>Mek,Tank,VTOL,Infantry,AeroSpaceFighter,Conventional Fighter</option>
		</unitType>
		
		<eschelon>
			<option ifUnitType="Mek|Tank|VTOL">%REGIMENT%,%BATTALION%,%COMPANY%,%LANCE%</option>
			<option ifUnitType="Infantry">%REGIMENT%,%BATTALION%,%COMPANY%</option>
			<option ifUnitType="BattleArmor">%BATTALION%,%COMPANY%,%PLATOON%</option>
			<option ifUnitType="AeroSpaceFighter|Conventional Fighter">%WING%,%SQUADRON%,%FLIGHT%</option>
		</eschelon>
		
		<rating>
			<option>A,B,C,D,F</option>
		</rating>
	</toc>
	
	<force eschelon="%REGIMENT%" eschName="Regiment" ifUnitType="Mek">
		<name ifFaction="MOC.MRG">{ordinal} Canopian Cuirassiers</name>
		<name ifFaction="MOC.CC">{ordinal} Canopian Light Horse</name>
		<name ifFaction="MOC.CF">{ordinal} Canopian Fusiliers</name>
		<name ifFaction="MOC.MH">{ordinal} Magistracy Highlanders</name>
		<name ifFaction="MOC.RC">{ordinal} Raventhir Cuirassiers</name>
		<co>%COLONEL%</co>
		
		<weightClass>
			<option weight="1">H</option>
			<option weight="3">M</option>
			<option weight="2">L</option>
		</weightClass>
		
		<subforces>
			<subforceOption ifWeightClass="A">
				<option weightClass="A,H,H">%BATTALION%</option>
				<option weightClass="A,H,M">%BATTALION%</option>
				<option weightClass="A,H,L">%BATTALION%</option>
				<option weightClass="A,M,M" weight="2">%BATTALION%</option>
				<option weightClass="A,M,L" weight="2">%BATTALION%</option>
			</subforceOption>
			<subforceOption ifWeightClass="H">
				<option weightClass="H,H,H">%BATTALION%</option>
				<option weightClass="H,H,M">%BATTALION%</option>
				<option weightClass="H,H,L" weight="2">%BATTALION%</option>
				<option weightClass="H,M,M" weight="3">%BATTALION%</option>
				<option weightClass="H,M,L" weight="2">%BATTALION%</option>
			</subforceOption>
			<subforceOption ifWeightClass="M">
				<option weightClass="H,M,M" weight="2">%BATTALION%</option>
				<option weightClass="H,M,L">%BATTALION%</option>
				<option weightClass="M,M,M" weight="3">%BATTALION%</option>
				<option weightClass="M,M,L" weight="2">%BATTALION%</option>
			</subforceOption>
			<subforceOption ifWeightClass="L">
				<option weightClass="H,L,L">%BATTALION%</option>
				<option weightClass="M,M,L" weight="2">%BATTALION%</option>
				<option weightClass="M,L,L" weight="3">%BATTALION%</option>
				<option weightClass="L,L,L">%BATTALION%</option>
			</subforceOption>
		</subforces>

		<attachedForces>
			<subforceOption ifFaction="MOC.MRG">
				<option unitType="AeroSpaceFighter" ifDateBetween=",3070"
					name="Air Guard">%FLIGHT%</option>
				<option unitType="AeroSpaceFighter" ifDateBetween="3056,3080"
					name="Air Guard">%SQUADRON%-</option>
				<option unitType="AeroSpaceFighter" ifDateBetween="3060,3090"
					name="Air Guard">%SQUADRON%</option>
				<option unitType="AeroSpaceFighter" ifDateBetween="3065,3110"
					name="Air Guard">%WING%-</option>
				<option unitType="AeroSpaceFighter" ifDateBetween="3080,"
					name="Air Guard">%WING%</option>
			</subforceOption>
			<subforceOption ifFaction="MOC.CC">
				<option ifDateBetween=",3070"/>
				<option unitType="AeroSpaceFighter" ifDateBetween="3060,3075"
					name="Air Guard">%FLIGHT%</option>
				<option unitType="AeroSpaceFighter" ifDateBetween="3066,3085"
					name="Air Guard">%SQUADRON%-</option>
				<option unitType="AeroSpaceFighter" ifDateBetween="3071,3100"
					name="Air Guard">%SQUADRON%</option>
				<option unitType="AeroSpaceFighter" ifDateBetween="3076,"
					name="Air Guard">%WING%-</option>
				<option unitType="AeroSpaceFighter" ifDateBetween="3080,"
					name="Air Guard">%WING%</option>
			</subforceOption>
			<subforceOption ifFaction="!MOC.MH">
				<option unitType="Tank"
					name="Armor Guard" weight="3">%REGIMENT%-</option>
				<option unitType="Tank"
					name="Armor Guard" weight="3">%BATTALION%</option>
				<option/>
			</subforceOption>
			<subforceOption>
				<option unitType="Infantry"
					name="Infantry Guard">%REGIMENT%</option>			
				<option unitType="Infantry" weight="11"
					name="Infantry Guard">%BATTALION%</option>			
			</subforceOption>
		</attachedForces>
	</force>
	
	<force eschelon="%REGIMENT%" eschName="Regiment" ifUnitType="Infantry">
		<name ifDateBetween=",3062" ifFaction="MOC.RC">{ordinal} Raventhir Footmen</name>
		<co>%COLONEL%</co>
		
		<weightClass>
			<option weight="1">A</option>
			<option weight="2">H</option>
			<option weight="4">M</option>
			<option weight="3">L</option>
		</weightClass>

		<subforces>
			<asParent/>
		</subforces>
	</force>
	
	<force eschelon="%COMPANY%" eschName="Company" ifUnitType="Infantry"
			ifRole="artillery|missile_artillery">
		<name>{ordinal} Field Artillery Company</name>
		<co>%CAPTAIN%</co>

		<subforces generate="group">
			<subforce num="3">%PLATOON%</subforce>
		</subforces>
	</force>
	
	<force eschelon="%COMPANY%" eschName="Company" ifUnitType="Infantry|BattleArmor">
		<name>{alpha} Company</name>
		<co>%CAPTAIN%</co>
		
		<unitType ifUnitType="Infantry" ifDateBetween="3051,"
				ifRole="">
			<option weight="1">BattleArmor</option>
			<option weight="11" ifDateBetween="3055,3060">Infantry</option>
			<option weight="9" ifDateBetween="3061,3075">Infantry</option>
			<option weight="7" ifDateBetween="3076,">Infantry</option>
		</unitType>
		
		<weightClass>
			<option weight="1">A</option>
			<option weight="2">H</option>
			<option weight="4">M</option>
			<option weight="3">L</option>
		</weightClass>
		
		<ruleGroup>
			<role ifUnitType="Infantry">
				<option weight="1">anti_mek</option>
				<option />
				<option ifWeightClass="H" weight="3" />
				<option ifWeightClass="M|L" weight="17" />
			</role>
			
			<variant ifWeightClass="H|A" ifUnitType="Infantry">
				<option weight="1">(Laser),(SRM)</option>
				<option />
			</variant>

			<motive ifUnitType="Infantry">
				<option weight="1" ifWeightClass="1">Jump</option>
				<option weight="2">Hover</option>
				<option weight="1">Wheeled</option>
				<option weight="3">Motorized</option>
				<option weight="12">Leg</option>
				<option weight="12" ifWeightClass="H|A">Leg</option>
				<option weight="9"/>
			</motive>
		</ruleGroup>

		<subforces ifUnitType="Infantry" generate="group">
			<subforce num="3">%PLATOON%</subforce>
		</subforces>

		<subforces ifUnitType="BattleArmor">
			<subforce num="4">%PLATOON%</subforce>
		</subforces>
	</force>

	<force eschelon="%FLIGHT%" eschName="Air Lance" ifUnitType="AeroSpaceFighter|Conventional Fighter">
		<co>%LT%</co>
		
		<weightClass>
			<option>H</option>
			<option>M</option>
			<option>L</option>
		</weightClass>

		<ruleGroup>
			<formation>
				<option weight="3" ifWeightClass="L|M">Aerospace Superiority Squadron</option>
				<option>Fire Support Squadron</option>
				<option weight="2" ifWeightClass="L|M">Interceptor Squadron</option>
				<option weight="3" ifWeightClass="M|H">Strike Squadron</option>
			</formation>
		</ruleGroup>

		<subforces generate="group">
			<subforce num="2">%ELEMENT%</subforce>
		</subforces>
	</force>
</ruleset>

=== MegaMek/megamek/megamek/data/forcegenerator/faction_rules/NC.xml
<?xml version="1.0" encoding="utf-8"?>

<!-- The Castillian military is modeled closely on the Umayyad Caliphate, which combines
Meks, armor, and infantry in all units above lance size. Forces are combined into brigadas
of six regiments each. No mention is made of aerospace units, but one or two wings per
brigada seems reasonable. -->

<ruleset faction="NC" parent="UC" ratingSystem="IS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="formationRulesetSchema.xsd">

	<defaults>
		<eschelon>%BRIGADE%</eschelon>
		<rankSystem>%RANK_CUSTOM%</rankSystem>
		<rating>C</rating>
	</defaults>
	
	<customRanks>
		<rank>%E1%:Caballero</rank>
		<rank>%LT%:Captain</rank>
		<rank>%CAPTAIN%:Major</rank>
		<rank>%MAJOR%:Comandante</rank>
		<rank>%COLONEL%:Principe</rank>
	</customRanks>

	<toc>
		<unitType>
			<option>null,Mek,Tank,VTOL,Infantry,AeroSpaceFighter,Conventional Fighter</option>
		</unitType>
		
		<eschelon>
			<option ifUnitType="">%BRIGADE%,%REGIMENT%,%BATTALION%,%COMPANY%</option>
			<option ifUnitType="Mek|Tank|VTOL">%LANCE%</option>
			<option ifUnitType="Infantry">%PLATOON%</option>
			<option ifUnitType="AeroSpaceFighter|Conventional Fighter">%WING%,%SQUADRON%,%FLIGHT%</option>
		</eschelon>
		
		<rating>
			<option>A,B,C,D,F</option>
		</rating>
	</toc>
	
	<force eschelon="%BRIGADE%" eschName="Brigada">
		<co>%COLONEL%</co>
		
		<subforces>
			<subforce num="6">%REGIMENT%</subforce>
		</subforces>
		
		<attachedForces>
			<subforce num="2" unitType="AeroSpaceFighter">%WING%</subforce>
		</attachedForces>
	</force>

	<!-- FM:Update gives the total Mek strength at about two regiments, which gives about
	works out to about one Mek lance for every four companies. -->
	
	<force eschelon="%COMPANY%" eschName="Company" ifUnitType="">
		<name ifRole="command">Command Company</name>
		<name>{formation} Company</name>
		<co>%CAPTAIN%</co>
		
		<weightClass>
			<option weight="1">A</option>
			<option weight="3">H</option>
			<option weight="5">M</option>
			<option weight="3">L</option>
		</weightClass>
		
		<subforces>
			<subforceOption ifWeightClass="A">
				<option weightClass="A" weight="2" unitType="Mek">%LANCE%</option>
				<option weightClass="H" weight="1" unitType="Mek">%LANCE%</option>
				<option weightClass="A" weight="6" unitType="Tank">%LANCE%</option>
				<option weightClass="H" weight="3" unitType="Tank">%LANCE%</option>
			</subforceOption>
			<subforceOption ifWeightClass="H">
				<option weightClass="H" weight="2" unitType="Mek">%LANCE%</option>
				<option weightClass="M" weight="1" unitType="Mek">%LANCE%</option>
				<option weightClass="H" weight="6" unitType="Tank">%LANCE%</option>
				<option weightClass="M" weight="3" unitType="Tank">%LANCE%</option>
			</subforceOption>
			<subforceOption ifWeightClass="M">
				<option weightClass="H" weight="1" unitType="Mek">%LANCE%</option>
				<option weightClass="M" weight="2" unitType="Mek">%LANCE%</option>
				<option weightClass="L" weight="1" unitType="Mek">%LANCE%</option>
				<option weightClass="H" weight="3" unitType="Tank">%LANCE%</option>
				<option weightClass="M" weight="6" unitType="Tank">%LANCE%</option>
				<option weightClass="L" weight="3" unitType="Tank">%LANCE%</option>
			</subforceOption>
			<subforceOption ifWeightClass="L">
				<option weightClass="M" weight="1" unitType="Mek">%LANCE%</option>
				<option weightClass="L" weight="2" unitType="Mek">%LANCE%</option>
				<option weightClass="M" weight="3" unitType="Tank">%LANCE%</option>
				<option weightClass="L" weight="6" unitType="Tank">%LANCE%</option>
			</subforceOption>
			
			<subforceOption ifWeightClass="A">
				<option weightClass="A" weight="2" unitType="Tank">%LANCE%</option>
				<option weightClass="H" weight="1" unitType="Tank">%LANCE%</option>
				<option weightClass="A" unitType="Infantry">%PLATOON%</option>
				<option weightClass="H" unitType="Infantry">%PLATOON%</option>
				<option weightClass="M" unitType="Infantry">%PLATOON%</option>
			</subforceOption>
			<subforceOption ifWeightClass="H">
				<option weightClass="H" weight="2" unitType="Tank">%LANCE%</option>
				<option weightClass="M" weight="1" unitType="Tank">%LANCE%</option>
				<option weightClass="H" unitType="Infantry">%PLATOON%</option>
				<option weightClass="M" weight="2" unitType="Infantry">%PLATOON%</option>
			</subforceOption>
			<subforceOption ifWeightClass="M">
				<option weightClass="H" weight="1" unitType="Tank">%LANCE%</option>
				<option weightClass="M" weight="2" unitType="Tank">%LANCE%</option>
				<option weightClass="L" weight="1" unitType="Tank">%LANCE%</option>
				<option weightClass="H" weight="1" unitType="Infantry">%LANCE%</option>
				<option weightClass="M" weight="2" unitType="Infantry">%LANCE%</option>
				<option weightClass="L" weight="1" unitType="Infantry">%LANCE%</option>
			</subforceOption>
			<subforceOption ifWeightClass="L">
				<option weightClass="M" weight="1" unitType="Tank">%LANCE%</option>
				<option weightClass="L" weight="2" unitType="Tank">%LANCE%</option>
				<option weightClass="M" weight="2" unitType="Infantry">%LANCE%</option>
				<option weightClass="L" weight="1" unitType="Infantry">%LANCE%</option>
			</subforceOption>			

			<subforceOption ifWeightClass="A">
				<option weightClass="A" unitType="Infantry">%PLATOON%</option>
				<option weightClass="H" unitType="Infantry">%PLATOON%</option>
				<option weightClass="M" unitType="Infantry">%PLATOON%</option>
			</subforceOption>
			<subforceOption ifWeightClass="H">
				<option weightClass="H" unitType="Infantry">%PLATOON%</option>
				<option weightClass="M" weight="2" unitType="Infantry">%PLATOON%</option>
			</subforceOption>
			<subforceOption ifWeightClass="M">
				<option weightClass="H" weight="1" unitType="Infantry">%LANCE%</option>
				<option weightClass="M" weight="2" unitType="Infantry">%LANCE%</option>
				<option weightClass="L" weight="1" unitType="Infantry">%LANCE%</option>
			</subforceOption>
			<subforceOption ifWeightClass="L">
				<option weightClass="M" weight="2" unitType="Infantry">%LANCE%</option>
				<option weightClass="L" weight="1" unitType="Infantry">%LANCE%</option>
			</subforceOption>			
		</subforces>		
	</force>
</ruleset>
