=== MegaMek/megamek/megamek/data/forcegenerator/faction_rules/formationRulesetSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<xs:attributeGroup name="predicateAttributeGroup">
		<xs:attribute name="ifUnitType" type="xs:string" />
		<xs:attribute name="ifWeightClass" type="xs:string" />
		<xs:attribute name="ifRating" type="xs:string" />
		<xs:attribute name="ifFormation" type="xs:string" />
		<xs:attribute name="ifRole" type="xs:string" />
		<xs:attribute name="ifMotive" type="xs:string" />
		<xs:attribute name="ifAugmented" type="xs:boolean" />
		<xs:attribute name="ifDateBetween" type="xs:string" />
		<xs:attribute name="ifTopLevel" type="xs:boolean" />
		<xs:attribute name="ifName" type="xs:string" />
		<xs:attribute name="ifFaction" type="xs:string" />
		<xs:attribute name="ifFlags" type="xs:string" />
		<xs:attribute name="ifIndex" type="xs:string" />
	</xs:attributeGroup>

	<xs:attributeGroup name="assertionAttributeGroup">
		<xs:attribute name="unitType" type="xs:string" />
		<xs:attribute name="weightClass" type="xs:string" />
		<xs:attribute name="rating" type="xs:string" />
		<xs:attribute name="formation" type="xs:string" />
		<xs:attribute name="role" type="xs:string" />
		<xs:attribute name="motive" type="xs:string" />
		<xs:attribute name="augmented" type="xs:boolean" />
		<xs:attribute name="chassis" type="xs:string" />
		<xs:attribute name="model" type="xs:string" />
		<xs:attribute name="variant" type="xs:string" />
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="fluffName" type="xs:string" />
		<xs:attribute name="faction" type="xs:string" />
		<xs:attribute name="flags" type="xs:string" />
	</xs:attributeGroup>

	<xs:group name="ruleGroup">
		<xs:choice>
			<xs:element name="weightClass" type="optionGroupType" />
			<xs:element name="unitType" type="optionGroupType" />
			<xs:element name="chassis" type="optionGroupType" />
			<xs:element name="variant" type="optionGroupType" />
			<xs:element name="motive" type="optionGroupType" />
			<xs:element name="formation" type="optionGroupType" />
			<xs:element name="role" type="optionGroupType" />
			<xs:element name="flags" type="optionGroupType" />
			<xs:element name="changeEschelon" type="optionGroupType" />
		</xs:choice>
	</xs:group>

	<xs:element name="ruleset">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="defaults" />
				<xs:element minOccurs="0" maxOccurs="1" ref="customRanks" />
				<xs:element minOccurs="0" maxOccurs="1" ref="toc" />
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="force" />
			</xs:sequence>
			<xs:attribute name="faction" type="xs:string" />
			<xs:attribute name="parent" type="xs:string" />
			<xs:attribute name="ratingSystem">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="IS|SL|CLAN|ROS" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="defaults">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="unitType">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attributeGroup
									ref="predicateAttributeGroup" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="eschelon">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attributeGroup
									ref="predicateAttributeGroup" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="rankSystem">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attributeGroup
									ref="predicateAttributeGroup" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="rating">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attributeGroup
									ref="predicateAttributeGroup" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="toc">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="1" name="unitType" type="tocType" />
				<xs:element minOccurs="0" maxOccurs="1" name="eschelon" type="tocType" />
				<xs:element minOccurs="0" maxOccurs="1" name="rating" type="tocType" />
				<xs:element minOccurs="0" maxOccurs="1" name="flags" type="tocType" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="customRanks">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" name="base" type="xs:string" />
				<xs:element maxOccurs="unbounded" name="rank">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value=".+:.+" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="force">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" minOccurs="0"
					maxOccurs="unbounded">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attributeGroup
									ref="predicateAttributeGroup" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="co" type="commanderType"
					maxOccurs="unbounded" />
				<xs:element name="xo" type="commanderType"
					minOccurs="0" maxOccurs="unbounded" />
				<xs:group ref="ruleGroup"
					minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="ruleGroup" type="ruleGroupType"
					minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="subforces" type="subforcesType"
					minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="attachedForces"
					type="subforcesType"
					minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>

			<xs:attribute name="eschelon" type="xs:string" use="required" />
			<xs:attribute name="eschName" type="xs:string" />
			<xs:attributeGroup ref="predicateAttributeGroup" />
		</xs:complexType>
	</xs:element>

	<xs:complexType name="tocType">
		<xs:sequence>
			<xs:element name="option" type="tocOptionType"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="tocOptionType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="ifEschelon" type="xs:string" />
				<xs:attributeGroup ref="predicateAttributeGroup" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="commanderType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="position" type="xs:integer" />
				<xs:attribute name="title" type="xs:string" />
				<xs:attribute name="unitType" type="xs:string" />
				<xs:attributeGroup ref="predicateAttributeGroup" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="ruleGroupType">
		<xs:sequence>
			<xs:group ref="ruleGroup" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="optionGroupType">
		<xs:sequence>
			<xs:element name="option" type="optionType"
				maxOccurs="unbounded" />
		</xs:sequence>

		<xs:attributeGroup ref="predicateAttributeGroup" />
	</xs:complexType>

	<xs:complexType name="optionType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="ifYearBetween" type="xs:string" />
				<xs:attribute name="weight" type="xs:integer"
					default="1" />
				<xs:attribute name="num" type="xs:integer" />
				<xs:attributeGroup ref="predicateAttributeGroup" />
				<xs:attributeGroup ref="assertionAttributeGroup" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="subforcesType">
		<xs:choice>
			<xs:element name="asFaction" type="xs:string" />
			<xs:element name="asParent" type="xs:string" />
			<xs:choice maxOccurs="unbounded">
				<xs:element name="subforce" type="subforceType" />
				<xs:element name="subforceOption"
					type="subforceOptionType" />
			</xs:choice>
		</xs:choice>

		<xs:attributeGroup ref="predicateAttributeGroup" />
		<xs:attribute name="generate" type="generateType" />
	</xs:complexType>

	<xs:complexType name="subforceType">
		<xs:simpleContent>
			<xs:extension base="eschelonDefinition">
				<xs:attributeGroup ref="predicateAttributeGroup" />
				<xs:attributeGroup ref="assertionAttributeGroup" />
				<xs:attribute name="num" type="xs:integer" default="1" />
				<xs:attribute name="generate" type="generateType" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:simpleType name="generateType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="model" />
			<xs:enumeration value="chassis" />
			<xs:enumeration value="group" />
			<xs:enumeration value="unit" />
			<xs:enumeration value="" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="eschelonDefinition">
		<xs:restriction base="xs:string">
			<xs:pattern value="([0-9]+|%[A-Z_]+%)[+-^]?" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="subforceOptionType">
		<xs:sequence>
			<xs:element name="option" type="optionType"
				maxOccurs="unbounded" />
		</xs:sequence>

		<xs:attributeGroup ref="predicateAttributeGroup" />
		<xs:attribute name="generate" type="generateType" />
	</xs:complexType>

</xs:schema>

=== MegaMek/megamek/megamek/data/forcegenerator/faction_rules/UC.xml
<?xml version="1.0" encoding="utf-8"?>

<!-- Umayyad forces are organized into one corps 5 regiments and two of 3 regiments each.
All units above lance/platoon size contain a mixture of Meks, vehicles, and infantry,
with a total Mek component of 1-2 battalions. FM:P does not mention aerospace support,
but a wing per corps seemed reasonable. -->

<ruleset faction="UC" parent="Periphery" ratingSystem="IS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="formationRulesetSchema.xsd">

	<defaults>
		<eschelon>%BRIGADE%</eschelon>
		<rankSystem>%RANK_CUSTOM%</rankSystem>
		<rating>C</rating>
	</defaults>
	
	<customRanks>
		<rank>%E1%:Safiya</rank>
		<rank>%LT%:Amir 'ashara</rank>
		<rank>%CAPTAIN%:Amir kabir</rank>
		<rank>%MAJOR%:Amir mi'a</rank>
		<rank>%COLONEL%:Atabeg</rank>
	</customRanks>

	<toc>
		<unitType>
			<option>null,Mek,Tank,VTOL,Infantry,AeroSpaceFighter,Conventional Fighter</option>
		</unitType>
		
		<eschelon>
			<option ifUnitType="">%BRIGADE%,%REGIMENT%,%BATTALION%,%COMPANY%</option>
			<option ifUnitType="Mek|Tank|VTOL">%LANCE%</option>
			<option ifUnitType="Infantry">%PLATOON%</option>
			<option ifUnitType="AeroSpaceFighter|Conventional Fighter">%WING%,%SQUADRON%,%FLIGHT%</option>
		</eschelon>
		
		<rating>
			<option>A,B,C,D,F</option>
		</rating>
	</toc>
	
	<force eschelon="%BRIGADE%" eschName="Corps">
		<co>%COLONEL%</co>
		
		<subforces>
			<subforceOption>
				<option num="5">%REGIMENT%</option>
				<option num="3" weight="2">%REGIMENT%</option>
			</subforceOption>
		</subforces>
		
		<attachedForces>
			<subforce unitType="AeroSpaceFighter">%WING%</subforce>
		</attachedForces>
	</force>

	<force eschelon="%REGIMENT%" eschName="Regiment" ifUnitType="">
		<co>%COLONEL%</co>
		
		<weightClass>
			<option weight="1">H</option>
			<option weight="3">M</option>
			<option weight="2">L</option>
		</weightClass>
		
		<subforces>
			<subforceOption ifWeightClass="A">
				<option weightClass="A,H,H">%BATTALION%</option>
				<option weightClass="A,H,M">%BATTALION%</option>
				<option weightClass="A,H,L">%BATTALION%</option>
				<option weightClass="A,M,M" weight="2">%BATTALION%</option>
				<option weightClass="A,M,L" weight="2">%BATTALION%</option>
			</subforceOption>
			<subforceOption ifWeightClass="H">
				<option weightClass="H,H,H">%BATTALION%</option>
				<option weightClass="H,H,M">%BATTALION%</option>
				<option weightClass="H,H,L" weight="2">%BATTALION%</option>
				<option weightClass="H,M,M" weight="3">%BATTALION%</option>
				<option weightClass="H,M,L" weight="2">%BATTALION%</option>
			</subforceOption>
			<subforceOption ifWeightClass="M">
				<option weightClass="H,M,M" weight="2">%BATTALION%</option>
				<option weightClass="H,M,L">%BATTALION%</option>
				<option weightClass="M,M,M" weight="3">%BATTALION%</option>
				<option weightClass="M,M,L" weight="2">%BATTALION%</option>
			</subforceOption>
			<subforceOption ifWeightClass="L">
				<option weightClass="H,L,L">%BATTALION%</option>
				<option weightClass="M,M,L" weight="2">%BATTALION%</option>
				<option weightClass="M,L,L" weight="3">%BATTALION%</option>
				<option weightClass="L,L,L">%BATTALION%</option>
			</subforceOption>
		</subforces>
	</force>
	
	<force eschelon="%BATTALION%" eschName="Battalion" ifUnitType="">
		<name>{ordinal} Battalion</name>
		<co>%MAJOR%</co>
		
		<weightClass>
			<option weight="1">A</option>
			<option weight="4">H</option>
			<option weight="6">M</option>
			<option weight="4">L</option>
		</weightClass>
		
		<subforces>
			<subforceOption ifWeightClass="A">
				<option weightClass="A,A,A">%COMPANY%</option>
				<option weightClass="A,A,H" weight="2">%COMPANY%</option>
				<option weightClass="A,H,H" weight="3">%COMPANY%</option>
			</subforceOption>
			<subforceOption ifWeightClass="H">
				<option weightClass="A,H,H">%COMPANY%</option>
				<option weightClass="H,H,H" weight="2">%COMPANY%</option>
				<option weightClass="H,H,M" weight="3">%COMPANY%</option>
			</subforceOption>
			<subforceOption ifWeightClass="M">
				<option weightClass="H,M,M">%COMPANY%</option>
				<option weightClass="M,M,M" weight="2">%COMPANY%</option>
				<option weightClass="M,M,L">%COMPANY%</option>
			</subforceOption>
			<subforceOption ifWeightClass="L">
				<option weightClass="M,M,L" weight="2">%COMPANY%</option>
				<option weightClass="M,L,L" weight="2">%COMPANY%</option>
				<option weightClass="L,L,L">%COMPANY%</option>
			</subforceOption>
		</subforces>
	</force>
	
	<!-- Giving each company a 50% chance of having a Mek regiment should give each corps
	1-2 battalions total. The first lance will be either Mek or armor, the second either
	armor or infantry, and the third will always be infantry. -->
	
	<force eschelon="%COMPANY%" eschName="Company" ifUnitType="">
		<name ifRole="command">Command Company</name>
		<name>{alpha} Company</name>
		<co>%CAPTAIN%</co>
		
		<weightClass>
			<option weight="1">A</option>
			<option weight="3">H</option>
			<option weight="5">M</option>
			<option weight="3">L</option>
		</weightClass>
		
		<subforces>
			<subforceOption ifWeightClass="A">
				<option weightClass="A" weight="2" unitType="Mek">%LANCE%</option>
				<option weightClass="H" weight="1" unitType="Mek">%LANCE%</option>
				<option weightClass="A" weight="2" unitType="Tank">%LANCE%</option>
				<option weightClass="H" weight="1" unitType="Tank">%LANCE%</option>
			</subforceOption>
			<subforceOption ifWeightClass="H">
				<option weightClass="H" weight="2" unitType="Mek">%LANCE%</option>
				<option weightClass="M" weight="1" unitType="Mek">%LANCE%</option>
				<option weightClass="H" weight="2" unitType="Tank">%LANCE%</option>
				<option weightClass="M" weight="1" unitType="Tank">%LANCE%</option>
			</subforceOption>
			<subforceOption ifWeightClass="M">
				<option weightClass="H" weight="1" unitType="Mek">%LANCE%</option>
				<option weightClass="M" weight="2" unitType="Mek">%LANCE%</option>
				<option weightClass="L" weight="1" unitType="Mek">%LANCE%</option>
				<option weightClass="H" weight="1" unitType="Tank">%LANCE%</option>
				<option weightClass="M" weight="2" unitType="Tank">%LANCE%</option>
				<option weightClass="L" weight="1" unitType="Tank">%LANCE%</option>
			</subforceOption>
			<subforceOption ifWeightClass="L">
				<option weightClass="M" weight="1" unitType="Mek">%LANCE%</option>
				<option weightClass="L" weight="2" unitType="Mek">%LANCE%</option>
				<option weightClass="M" weight="1" unitType="Tank">%LANCE%</option>
				<option weightClass="L" weight="2" unitType="Tank">%LANCE%</option>
			</subforceOption>
			
			<subforceOption ifWeightClass="A">
				<option weightClass="A" weight="2" unitType="Tank">%LANCE%</option>
				<option weightClass="H" weight="1" unitType="Tank">%LANCE%</option>
				<option weightClass="A" unitType="Infantry">%PLATOON%</option>
				<option weightClass="H" unitType="Infantry">%PLATOON%</option>
				<option weightClass="M" unitType="Infantry">%PLATOON%</option>
			</subforceOption>
			<subforceOption ifWeightClass="H">
				<option weightClass="H" weight="2" unitType="Tank">%LANCE%</option>
				<option weightClass="M" weight="1" unitType="Tank">%LANCE%</option>
				<option weightClass="H" unitType="Infantry">%PLATOON%</option>
				<option weightClass="M" weight="2" unitType="Infantry">%PLATOON%</option>
			</subforceOption>
			<subforceOption ifWeightClass="M">
				<option weightClass="H" weight="1" unitType="Tank">%LANCE%</option>
				<option weightClass="M" weight="2" unitType="Tank">%LANCE%</option>
				<option weightClass="L" weight="1" unitType="Tank">%LANCE%</option>
				<option weightClass="H" weight="1" unitType="Infantry">%LANCE%</option>
				<option weightClass="M" weight="2" unitType="Infantry">%LANCE%</option>
				<option weightClass="L" weight="1" unitType="Infantry">%LANCE%</option>
			</subforceOption>
			<subforceOption ifWeightClass="L">
				<option weightClass="M" weight="1" unitType="Tank">%LANCE%</option>
				<option weightClass="L" weight="2" unitType="Tank">%LANCE%</option>
				<option weightClass="M" weight="2" unitType="Infantry">%LANCE%</option>
				<option weightClass="L" weight="1" unitType="Infantry">%LANCE%</option>
			</subforceOption>			

			<subforceOption ifWeightClass="A">
				<option weightClass="A" unitType="Infantry">%PLATOON%</option>
				<option weightClass="H" unitType="Infantry">%PLATOON%</option>
				<option weightClass="M" unitType="Infantry">%PLATOON%</option>
			</subforceOption>
			<subforceOption ifWeightClass="H">
				<option weightClass="H" unitType="Infantry">%PLATOON%</option>
				<option weightClass="M" weight="2" unitType="Infantry">%PLATOON%</option>
			</subforceOption>
			<subforceOption ifWeightClass="M">
				<option weightClass="H" weight="1" unitType="Infantry">%LANCE%</option>
				<option weightClass="M" weight="2" unitType="Infantry">%LANCE%</option>
				<option weightClass="L" weight="1" unitType="Infantry">%LANCE%</option>
			</subforceOption>
			<subforceOption ifWeightClass="L">
				<option weightClass="M" weight="2" unitType="Infantry">%LANCE%</option>
				<option weightClass="L" weight="1" unitType="Infantry">%LANCE%</option>
			</subforceOption>			
		</subforces>		
	</force>
</ruleset>

=== MegaMek/megamek/megamek/data/forcegenerator/faction_rules/CFM.PBG.xml
<?xml version="1.0" encoding="utf-8"?>

<ruleset faction="CFM.PBG" ratingSystem="CLAN" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="formationRulesetSchema.xsd">

	<defaults>
		<eschelon>%CLUSTER%</eschelon>
		<rankSystem>%RANK_CUSTOM%</rankSystem>
		<rating>FL</rating>
	</defaults>
	
	<toc>
		<unitType>
			<option ifDateBetween="3060,">null,Mek,ProtoMek,Tank,VTOL,Infantry,BattleArmor,AeroSpaceFighter,Conventional Fighter</option>
			<option ifDateBetween="2870,3059">null,Mek,Tank,VTOL,Infantry,BattleArmor,AeroSpaceFighter,Conventional Fighter</option>
			<option ifDateBetween=",2869">null,Mek,Tank,VTOL,Infantry,AeroSpaceFighter,Conventional Fighter</option>
		</unitType>
		
		<eschelon>
			<option ifUnitType="">%GALAXY%,%CLUSTER%</option>
			<option ifUnitType="Mek|AeroSpaceFighter" ifDateBetween="2870,">%TRINARY%^,%TRINARY%,%BINARY%^,%BINARY%,%STAR%^,%STAR%</option>
			<option>%TRINARY%,%BINARY%,%STAR%</option>
		</eschelon>
		
		<rating>
			<option ifUnitType="Tank|VTOL">SL:Second Line,PG:Garrison,Sol:Solahma</option>
			<option ifUnitType="Infantry" ifDateBetween="2900,">PG:Garrison,Sol:Solahma</option>
			<option ifUnitType="Infantry">PG:Garrison,Sol:Solahma</option>
			<option ifEschelon="%GALAXY%"></option>
			<option>Keshik,FL:Front Line,SL:Second Line,PG:Garrison,Sol:Solahma</option>
		</rating>
		
		<flags>
			<option ifUnitType="null|Mek|BattleArmor" ifEschelon="%TRINARY%|%BINARY%">mixedMekBA:Combined Mek/BA unit</option>
		</flags>
	</toc>
	
	<force eschelon="%GALAXY%" eschName="Kindraa">
		<co>%GALAXY_CMDR%</co>
		
		<subforces>
			<subforce role="command" rating="Keshik"
				unitType="Mek" faction="CFM.P">%TRINARY%</subforce>
			<subforceOption>
				<option num="1" rating="FL"
					faction="CFM.P">%CLUSTER%</option>
				<option num="2" rating="FL"
					faction="CFM.P">%CLUSTER%</option>
			</subforceOption>
			<subforce num="1" rating="FL" faction="CFM.BG"
				unitType="AeroSpaceFighter">%CLUSTER%</subforce>
			<subforce num="1" rating="SL"
				faction="CFM.BG">%CLUSTER%</subforce>
			<subforce num="1" rating="SL" flags="binary"
				faction="CFM.BG">%CLUSTER%</subforce>
		</subforces>
		
		<attachedForces>
			<subforce unitType="Warship" fluffName="CFM Reaver"
				chassis="Sovetskii Soyuz Heavy Cruiser">%ELEMENT%</subforce>
			<subforce unitType="Warship" fluffName="CFM Anathma"
				chassis="Lola III Destroyer"
				ifDateBetween=",3071">%ELEMENT%</subforce>
			<subforce unitType="Warship" fluffName="CFM Firehold"
				chassis="Carrack Transport">%ELEMENT%</subforce>
		</attachedForces>
	</force>
</ruleset>

=== MegaMek/megamek/megamek/data/forcegenerator/faction_rules/ROS.xml
<?xml version="1.0" encoding="utf-8"?>

<ruleset faction="ROS" parent="IS" ratingSystem="ROS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="formationRulesetSchema.xsd">

	<defaults>
		<unitType>Mek</unitType>
		<eschelon>%REGIMENT%</eschelon>
		<rankSystem>%RANK_SL%</rankSystem>
		<rating>HS</rating>
	</defaults>
	
	<customRanks>
		<rank>%LT_COLONEL%:Lieutenant Colonel,Commodore,--MW,--MW,--MW,--MW</rank>
	</customRanks>

	<toc>
		<unitType>
			<option>Mek,Tank,VTOL,Infantry,BattleArmor,AeroSpaceFighter,Conventional Fighter</option>
		</unitType>
		
		<eschelon>
			<option ifUnitType="Mek|Tank|VTOL">%REGIMENT%,%BATTALION%,%COMPANY%,%LANCE%</option>
			<option ifUnitType="Infantry">%REGIMENT%,%BATTALION%,%COMPANY%</option>
			<option ifUnitType="BattleArmor">%BATTALION%,%COMPANY%,%PLATOON%</option>
			<option ifUnitType="AeroSpaceFighter|Conventional Fighter">%REGIMENT%,%WING%,%SQUADRON%,%FLIGHT%</option>
		</eschelon>
		
		<rating>
			<option>SB:Stone&apos;s Brigade,HS:Hastati Sentinels,PG:Principes Guards,TP:Triarii Protectors</option>
		</rating>
	</toc>

	<force eschelon="%REGIMENT%" eschName="Regiment" ifUnitType="Mek|Tank">
		<co ifUnitType="Tank">%LT_COLONEL%</co>
		<co>%COLONEL%</co>
		
		<changeEschelon ifRating="TP" ifUnitType="Mek">
			<option>%BATTALION%</option>
		</changeEschelon>
		
		<weightClass>
			<option weight="1">L</option>
			<option weight="2">M</option>
			<option weight="1">H</option>
		</weightClass>
		
		<subforces ifRating="!PG">
			<asParent/>
		</subforces>
		
		<subforces ifRating="PG">
			<subforceOption ifWeightClass="H|A">
				<option weightClass="A,A">%BATTALION%</option>
				<option weightClass="A,H">%BATTALION%</option>
				<option weightClass="A,M">%BATTALION%</option>
				<option weightClass="A,H">%BATTALION%</option>
				<option weightClass="H,H">%BATTALION%</option>
				<option weightClass="H,M">%BATTALION%</option>
			</subforceOption>
			<subforceOption ifWeightClass="M">
				<option weightClass="H,M">%BATTALION%</option>
				<option weightClass="M,M">%BATTALION%</option>
				<option weightClass="M,L">%BATTALION%</option>
			</subforceOption>
			<subforceOption ifWeightClass="L">
				<option weightClass="M,L">%BATTALION%</option>
				<option weightClass="L,L">%BATTALION%</option>
			</subforceOption>
		</subforces>
		
		<attachedForces ifUnitType="Mek" ifRating="!SB">
			<subforce unitType="Tank">%BRIGADE%</subforce>
			<subforce unitType="Infantry">%BRIGADE%</subforce>
			<subforce unitType="AeroSpaceFighter">%WING%</subforce>
		</attachedForces>
		
		<attachedForces ifUnitType="Mek" ifRating="SB">
			<subforce unitType="Tank">%REGIMENT%</subforce>
			<subforce unitType="BattleArmor">%BATTALION%</subforce>
			<subforce unitType="AeroSpaceFighter">%WING%</subforce>
		</attachedForces>
	</force>
	
	<force eschelon="%BRIGADE%" eschName="Brigade" ifUnitType="Tank" ifRating="TP">
		<co>%COLONEL%</co>
		
		<subforces>
			<subforce num="3">%REGIMENT%</subforce>
		</subforces>
		
		<attachedForces>
			<subforce role="artillery">%BATTALION%</subforce>
		</attachedForces>
	</force>
	
	<force eschelon="%BRIGADE%" eschName="Brigade" ifUnitType="Tank">
		<co>%COLONEL%</co>
		
		<subforces>
			<subforce num="2">%REGIMENT%</subforce>
		</subforces>
		
		<attachedForces>
			<subforce role="artillery">%COMPANY%</subforce>
		</attachedForces>
	</force>
	
	<force eschelon="%BRIGADE%" eschName="Brigade" ifUnitType="Infantry">
		<co>%COLONEL%</co>
		
		<subforces>
			<subforce num="3">%REGIMENT%</subforce>
		</subforces>
	</force>
	
	<force eschelon="%BATTALION%" eschName="Battalion" ifUnitType="Mek" ifRating="TP">
		<name>{ordinal} Battalion</name>
		<co>%COLONEL%</co>
		
		<weightClass>
			<option weight="4">A</option>
			<option weight="9">H</option>
			<option weight="9">M</option>
			<option weight="7">L</option>
		</weightClass>
		
		<subforces>
			<asParent/>
		</subforces>
		
		<attachedForces>
			<subforce unitType="Tank">%BRIGADE%</subforce>
			<subforce unitType="Infantry">%BRIGADE%</subforce>
			<subforce unitType="AeroSpaceFighter">%WING%</subforce>
		</attachedForces>
	</force>
</ruleset>

=== MegaMek/megamek/megamek/data/forcegenerator/faction_rules/CFM.MiKrKl.xml
<?xml version="1.0" encoding="utf-8"?>

<ruleset faction="CFM.MiKrKl" ratingSystem="CLAN" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="formationRulesetSchema.xsd">

	<defaults>
		<eschelon>%CLUSTER%</eschelon>
		<rankSystem>%RANK_CUSTOM%</rankSystem>
		<rating>FL</rating>
	</defaults>
	
	<toc>
		<unitType>
			<option ifDateBetween="3060,">null,Mek,ProtoMek,Tank,VTOL,Infantry,BattleArmor,AeroSpaceFighter,Conventional Fighter</option>
			<option ifDateBetween="2870,3059">null,Mek,Tank,VTOL,Infantry,BattleArmor,AeroSpaceFighter,Conventional Fighter</option>
			<option ifDateBetween=",2869">null,Mek,Tank,VTOL,Infantry,AeroSpaceFighter,Conventional Fighter</option>
		</unitType>
		
		<eschelon>
			<option ifUnitType="">%GALAXY%,%CLUSTER%</option>
			<option ifUnitType="BattleArmor">%CLUSTER%,%TRINARY%^,%TRINARY%,%BINARY%^,%BINARY%,%STAR%^,%STAR%</option>
			<option ifUnitType="Mek|AeroSpaceFighter" ifDateBetween="2870,">%TRINARY%^,%TRINARY%,%BINARY%^,%BINARY%,%STAR%^,%STAR%</option>
			<option>%TRINARY%,%BINARY%,%STAR%</option>
		</eschelon>
		
		<rating>
			<option ifUnitType="Tank|VTOL">SL:Second Line,PG:Garrison,Sol:Solahma</option>
			<option ifUnitType="Infantry" ifDateBetween="2900,">PG:Garrison,Sol:Solahma</option>
			<option ifUnitType="Infantry">PG:Garrison,Sol:Solahma</option>
			<option ifEschelon="%GALAXY%"></option>
			<option>Keshik,FL:Front Line,SL:Second Line,PG:Garrison,Sol:Solahma</option>
		</rating>
		
		<flags>
			<option ifUnitType="null|Mek|BattleArmor" ifEschelon="%TRINARY%|%BINARY%">mixedMekBA:Combined Mek/BA unit</option>
			<option ifUnitType="null|Mek|AeroSpaceFighter" ifEschelon="%TRINARY%|%BINARY%">mixedMekAero:Combined Mek/Aero unit</option>
			<option ifUnitType="null|Mek|AeroSpaceFighter" ifEschelon="%STAR%|STAR^">mekAeroNova:Mek+Aero Nova</option>
		</flags>
	</toc>
	
	<force eschelon="%GALAXY%" eschName="Kindraa">
		<co>%GALAXY_CMDR%</co>
		
		<subforces>
			<subforce role="command" rating="Keshik"
				unitType="Mek" faction="CFM.Kl">%TRINARY%</subforce>
			<subforceOption>
				<option num="1" rating="FL"
					faction="CFM.MiKr">%CLUSTER%</option>
				<option num="2" rating="FL"
					faction="CFM.MiKr">%CLUSTER%</option>
			</subforceOption>
			<subforce num="1" rating="FL" faction="CFM.MiKr"
				unitType="AeroSpaceFighter">%CLUSTER%</subforce>
			<subforce num="1" rating="FL" faction="CFM.MiKr"
				unitType="BattleArmor">%CLUSTER%</subforce>
			<subforceOption>
				<option num="2" rating="SL"
					faction="CFM.Kl">%CLUSTER%</option>
				<option num="3" rating="SL"
					faction="CFM.Kl">%CLUSTER%</option>
			</subforceOption>
			<subforce rating="SL" faction="CFM.MiKr">%CLUSTER%</subforce>
		</subforces>

		<attachedForces>
			<subforce unitType="Warship" fluffName="CFM Jungle Fever"
				chassis="Potemkin Troop Cruiser"
				ifDateBetween=",3071">%ELEMENT%</subforce>
			<subforce unitType="Warship" fluffName="CFM Rancor"
				chassis="Lola III Destroyer"
				ifDateBetween=",3071">%ELEMENT%</subforce>
		</attachedForces>
	</force>
</ruleset>
